spring:
  datasource:
    username: sa
    password: sqlserver
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:sqlserver://localhost:1433
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

mybatis:
  type-aliases-package: com.example.bighomework.pojo

server:
  port: 2333

### FreeMarker 配置
spring.freemarker.allow-request-override: false
#Enable template caching.启用模板缓存。
spring.freemarker.cache: false
spring.freemarker.check-template-location: true
spring.freemarker.charset: UTF-8
spring.freemarker.content-type: text/html
spring.freemarker.expose-request-attributes: false
spring.freemarker.expose-session-attributes: false
spring.freemarker.expose-spring-macro-helpers: false
#设置面板后缀
spring.freemarker.suffix: .ftl

# 设置单个文件最大内存

# 设置所有文件最大内存

# 自定义文件上传路径
web.upload-path: D:/code_software/buaa_database/font-bighm/static/img/其它

